# Generated by Django 5.1.6 on 2025-04-18 01:13

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "email",
                    models.EmailField(editable=False, max_length=254, unique=True),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("batch", models.CharField(blank=True, default="", max_length=10)),
                ("school", models.CharField(blank=True, default="", max_length=100)),
                ("major", models.CharField(blank=True, default="", max_length=100)),
                (
                    "courses",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional: List courses separated by commas or new lines",
                    ),
                ),
                (
                    "interests",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional: List interests separated by commas or new lines",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.user_profile_pic_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
