# Generated by Django 5.1.6 on 2025-04-18 03:19

import feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_id",
            field=models.UUIDField(
                db_index=True, default=feed.models.default_uuid, editable=False
            ),
        ),
    ]
