# Generated by Django 5.1.6 on 2025-04-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_alter_post_author_name_comment_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author_id",
            field=models.CharField(db_index=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name="like",
            name="user_id",
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="post",
            name="author_id",
            field=models.CharField(db_index=True, editable=False, max_length=40),
        ),
    ]
