# Generated by Django 5.1.6 on 2025-04-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_alter_comment_author_id_alter_like_user_id_and_more"),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name="like",
        #     unique_together={("post", "user_name")},
        # ),
        migrations.AddField(
            model_name="like",
            name="user_name",
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.RemoveField(
            model_name="like",
            name="user_name",
        ),
    ]
