# Generated by Django 5.1.6 on 2025-04-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_alter_like_unique_together_like_user_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
    ]
