# Generated by Django 5.1.6 on 2025-04-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0006_alter_like_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="user_id",
        ),
        migrations.AddField(
            model_name="like",
            name="user_name",
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
