# Generated by Django 5.1.6 on 2025-04-21 01:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_remove_like_user_id_like_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author_id",
        ),
        migrations.AddField(
            model_name="like",
            name="user_id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("00000000-0000-0000-0000-000000000000"),
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="user_id",
            field=models.UUIDField(
                db_index=True, default=uuid.UUID("00000000-0000-0000-0000-000000000000")
            ),
        ),
    ]
