# Generated by Django 5.1.6 on 2025-04-21 01:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0009_post_author_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("00000000-0000-0000-0000-000000000000"),
                editable=False,
            ),
        ),
    ]
