# Generated by Django 5.1.6 on 2025-04-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0010_alter_post_author_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user_id",
        ),
    ]
