# Generated by Django 5.1.6 on 2025-04-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0011_remove_post_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
