# Generated by Django 5.1.6 on 2025-04-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0012_post_author_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author_email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
