# Generated by Django 5.1.6 on 2025-04-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0013_comment_author_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="deleted_by",
            field=models.CharField(
                blank=True,
                choices=[("AUTHOR", "Author"), ("POSTER", "Poster")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
