# Generated by Django 5.1.7 on 2025-04-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0015_community_communitymember_joinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="feed.community",
            ),
        ),
    ]
