# Generated by Django 5.1.7 on 2025-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0016_post_community"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
