# Generated by Django 5.1.7 on 2025-04-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0018_voicechannel_voicechannelparticipant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voicechannelparticipant",
            name="is_speaking",
        ),
        migrations.AlterField(
            model_name="voicechannelparticipant",
            name="display_name",
            field=models.CharField(max_length=255),
        ),
    ]
